name: Update QA Stand
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ["self-hosted", "k8s-prod"]
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable

      - name: Install modules
        run: |
          yarn install
      - name: Check external links
        run: |
          find ./README.md ./docs/ -regex ".*.[md|mdx]" -print0 | xargs -0 -n1 \
          ./node_modules/markdown-link-check/markdown-link-check --config linkcheck.config.json -q
      - name: Build
        run: |
          yarn clear
          yarn build


      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "6aa89f18f67a9754ebd563ed320efb8b"
          projectName: "docs-test"
          directory: "build"
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GHTOKEN }}
